name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  lint:
    name: run lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: ./.github/actions/setup-repo
      - run: pnpm run lint
  format:
    name: run format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: ./.github/actions/setup-repo
      - run: pnpm run format --check
  build:
    name: run build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: ./.github/actions/setup-repo
      - run: pnpm run build
  test:
    name: run test
    strategy:
      matrix:
        node_version: [22.x, 24.x, 26.x]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: ./.github/actions/setup-repo
        with:
          node-version: ${{ matrix.node_version }}
      - run: pnpm run test
